title: Madison Perry

email: meperryviola@gmail.com or mep7da@virginia.edu

description: > # this means to ignore newlines until "show_excerpts:"
  This is my personal (semi-professional) website, compiling samples of my work and updates about my research and career.
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: @MadisonEPerry
    github:  meperryviola
    
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- CV.markdown
- research.markdown
- papers.markdown

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

